# Generated by Django 5.2.8 on 2025-11-25 03:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('datetime', models.DateTimeField(verbose_name='Fecha y hora')),
                ('category', models.CharField(choices=[('estudiantes', 'Estudiantes por Equipos'), ('interfacultades', 'Interfacultades por Equipos')], max_length=20, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_running', models.BooleanField(default=False, verbose_name='En curso')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Juez',
                'verbose_name_plural': 'Jueces',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('number', models.PositiveIntegerField(verbose_name='Dorsal')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.competencia', verbose_name='Competencia')),
                ('judge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='app.juez', verbose_name='Juez asignado')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['number'],
                'unique_together': {('competition', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoEquipo',
            fields=[
            ],
            options={
                'verbose_name': 'Resultado por Equipo',
                'verbose_name_plural': 'Resultados por Equipo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.equipo',),
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de registro')),
                ('time', models.BigIntegerField(help_text='Tiempo en milisegundos', verbose_name='Tiempo')),
                ('hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas')),
                ('minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minutos')),
                ('seconds', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Segundos')),
                ('milliseconds', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Milisegundos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='app.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Registro de Tiempo',
                'verbose_name_plural': 'Registros de Tiempo',
                'ordering': ['time'],
                'indexes': [models.Index(fields=['team', 'time'], name='app_registr_team_id_8a10ff_idx')],
            },
        ),
    ]
