# Generated by Django 5.2.8 on 2025-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_juez_multiple_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='category',
        ),
        migrations.AddField(
            model_name='equipo',
            name='category',
            field=models.CharField(choices=[('estudiantes', 'Estudiantes por Equipos'), ('interfacultades', 'Interfacultades por Equipos')], default='estudiantes', max_length=20, verbose_name='Categoría'),
        ),
    ]
