"""add_date_of_birth_to_users

Revision ID: 0ce570dcc578
Revises: 19347d1dd699
Create Date: 2025-11-12 18:13:36.428497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce570dcc578'
down_revision: Union[str, Sequence[str], None] = '19347d1dd699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    
    # Set a default date for existing users (e.g., 2000-01-01)
    op.execute("UPDATE users SET date_of_birth = '2000-01-01' WHERE date_of_birth IS NULL")
    
    # Now make it not nullable
    op.alter_column('users', 'date_of_birth', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###