"""Add DNI field to users table

Revision ID: 19347d1dd699
Revises: 9b88e3366091
Create Date: 2025-11-11 17:20:04.326906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19347d1dd699'
down_revision: Union[str, Sequence[str], None] = '9b88e3366091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('users', sa.Column('dni', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_dni'), 'users', ['dni'], unique=True)
    
    # If you have existing data, update it here with default values
    # op.execute("UPDATE users SET dni = 'PENDING-' || id::text WHERE dni IS NULL")
    
    # Then make it NOT NULL
    op.alter_column('users', 'dni', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_dni'), table_name='users')
    op.drop_column('users', 'dni')
    # ### end Alembic commands ###