"""Primera migracion

Revision ID: 9a1daee44178
Revises: 
Create Date: 2025-11-28 01:15:26.950899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1daee44178'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('competition_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competence_id'), 'competence', ['id'], unique=False)
    op.create_index(op.f('ix_competence_name'), 'competence', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATOR', 'MODERATOR', name='roleenum'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_dni'), 'user', ['dni'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('competition_registration',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dorsal_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('n_participants', sa.Integer(), server_default='1', nullable=False),
    sa.Column('user_dni', sa.String(length=50), nullable=False),
    sa.Column('competence_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_registration_competence_id'), 'competition_registration', ['competence_id'], unique=False)
    op.create_index(op.f('ix_competition_registration_dorsal_number'), 'competition_registration', ['dorsal_number'], unique=False)
    op.create_index(op.f('ix_competition_registration_id'), 'competition_registration', ['id'], unique=False)
    op.create_index(op.f('ix_competition_registration_name'), 'competition_registration', ['name'], unique=False)
    op.create_index(op.f('ix_competition_registration_user_dni'), 'competition_registration', ['user_dni'], unique=False)
    op.create_table('time_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('competition_registration_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['competition_registration_id'], ['competition_registration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_record_competition_registration_id'), 'time_record', ['competition_registration_id'], unique=False)
    op.create_index(op.f('ix_time_record_id'), 'time_record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_record_id'), table_name='time_record')
    op.drop_index(op.f('ix_time_record_competition_registration_id'), table_name='time_record')
    op.drop_table('time_record')
    op.drop_index(op.f('ix_competition_registration_user_dni'), table_name='competition_registration')
    op.drop_index(op.f('ix_competition_registration_name'), table_name='competition_registration')
    op.drop_index(op.f('ix_competition_registration_id'), table_name='competition_registration')
    op.drop_index(op.f('ix_competition_registration_dorsal_number'), table_name='competition_registration')
    op.drop_index(op.f('ix_competition_registration_competence_id'), table_name='competition_registration')
    op.drop_table('competition_registration')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_dni'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_competence_name'), table_name='competence')
    op.drop_index(op.f('ix_competence_id'), table_name='competence')
    op.drop_table('competence')
    # ### end Alembic commands ###