"""Add tables competetition

Revision ID: d0b2d728a2a2
Revises: 65c7f6098c77
Create Date: 2025-11-13 00:16:53.730411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b2d728a2a2'
down_revision: Union[str, Sequence[str], None] = '65c7f6098c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('competition_date', sa.Date(), nullable=False),
    sa.Column('competition_limit_for_registration_date', sa.Date(), nullable=True),
    sa.Column('n_turns', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('start_coordinates', sa.JSON(), nullable=True),
    sa.Column('finish_coordinates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competences_external_id'), 'competences', ['external_id'], unique=True)
    op.create_index(op.f('ix_competences_id'), 'competences', ['id'], unique=False)
    op.create_index(op.f('ix_competences_name'), 'competences', ['name'], unique=False)
    op.create_table('competition_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('n_turns', sa.Integer(), nullable=True),
    sa.Column('user_dni', sa.String(length=50), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_registrations_competence_id'), 'competition_registrations', ['competence_id'], unique=False)
    op.create_index(op.f('ix_competition_registrations_external_id'), 'competition_registrations', ['external_id'], unique=True)
    op.create_index(op.f('ix_competition_registrations_id'), 'competition_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_competition_registrations_registration_number'), 'competition_registrations', ['registration_number'], unique=True)
    op.create_index(op.f('ix_competition_registrations_user_dni'), 'competition_registrations', ['user_dni'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_registrations_user_dni'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_registration_number'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_id'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_external_id'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_competence_id'), table_name='competition_registrations')
    op.drop_table('competition_registrations')
    op.drop_index(op.f('ix_competences_name'), table_name='competences')
    op.drop_index(op.f('ix_competences_id'), table_name='competences')
    op.drop_index(op.f('ix_competences_external_id'), table_name='competences')
    op.drop_table('competences')
    # ### end Alembic commands ###